#!/usr/bin/env python3
"""
wav2h.py - generate the sound headers of VectorArcade from its WAV files.

software/VectorArcade/data/*.wav is the single source of the sound clips:
  - SOUNDS_FROM_LITTLEFS() 1 loads them from LittleFS (uploaded from data/),
  - SOUNDS_FROM_LITTLEFS() 0 links them into the firmware from sounds/*.h,
    which this script generates: data/Pew.wav -> sounds/Pew.h, array cSoundPewWAV.

It also writes a fingerprint (CRC-32 over the names and contents of all WAV files) twice:
  - data/sounds.id, uploaded to LittleFS together with the WAV files,
  - sounds/SoundsId.h, compiled into the firmware (cSoundsId).
At startup the firmware compares the two, so WAV files that do not match the firmware are
reported instead of silently playing the wrong or no sound.

Usage (from anywhere; paths are relative to this script):
  python3 wav2h.py           regenerate sounds/*.h that are missing or out of date
  python3 wav2h.py --check   only report; exit code 1 if anything is missing or stale

Run it after every change in data/, then upload data/ again (including sounds.id).

Only 16-bit PCM WAV files are accepted, the format SoundEngine plays. A header is
rewritten only if its content changes, so unchanged clips do not trigger a recompile.
Python 3 standard library only.
"""

import argparse
import sys
import wave
import zlib
from pathlib import Path

SKETCH_DIR = Path(__file__).resolve().parent.parent / "VectorArcade"
DATA_DIR = SKETCH_DIR / "data"
SOUNDS_DIR = SKETCH_DIR / "sounds"
ID_FILE = DATA_DIR / "sounds.id"
ID_HEADER = SOUNDS_DIR / "SoundsId.h"
BYTES_PER_LINE = 16


def describe_wav(path):
    """Returns a one-line format description; raises ValueError if SoundEngine cannot play it."""
    try:
        with wave.open(str(path), "rb") as w:
            channels, width, rate, frames = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
            if w.getcomptype() != "NONE":
                raise ValueError("compressed WAV, PCM required")
    except wave.Error as e:
        raise ValueError(f"not a readable PCM WAV ({e})")
    if width != 2:
        raise ValueError(f"{8 * width}-bit samples, 16-bit required")
    layout = {1: "mono", 2: "stereo"}.get(channels, f"{channels} channels")
    return f"16-bit PCM WAV, {layout}, {rate} Hz, {frames / rate:.2f} s"


def render_header(name, data, description):
    lines = [
        "#pragma once",
        "",
        f"// Generated by software/tools/wav2h.py from data/{name}.wav - do not edit.",
        "// Change the WAV file and run the script again.",
        "//",
        f"// {description}, {len(data):,} bytes",
        "",
        f"const unsigned char cSound{name}WAV[] = {{",
    ]
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        last = i + BYTES_PER_LINE >= len(data)
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ("" if last else ","))
    lines += ["};", ""]
    return "\n".join(lines)


def fingerprint(wavs):
    """CRC-32 over the names and contents of the WAV files, as 8 hex digits."""
    crc = 0
    for wav in wavs:
        crc = zlib.crc32(wav.name.encode() + b"\0", crc)
        crc = zlib.crc32(wav.read_bytes(), crc)
    return f"{crc:08x}"


def render_id_header(sounds_id):
    return "\n".join([
        "#pragma once",
        "",
        "// Generated by software/tools/wav2h.py from data/*.wav - do not edit.",
        "// Fingerprint of the WAV files; data/sounds.id holds the same value.",
        "",
        f'constexpr const char* cSoundsId = "{sounds_id}";',
        "",
    ])


def update(path, content, check):
    """Writes path if its content differs. Returns True if it was (or, with check, would be) changed."""
    current = path.read_text() if path.exists() else None
    if current == content:
        print(f"ok     {path.name}")
        return False
    if check:
        print(f"{'STALE ' if current else 'MISSING'} {path.name}")
    else:
        path.parent.mkdir(exist_ok=True)
        path.write_text(content)
        print(f"{'updated' if current else 'created'} {path.name}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate sounds/*.h from data/*.wav")
    parser.add_argument("--check", action="store_true", help="report only, change nothing")
    args = parser.parse_args()

    wavs = sorted(DATA_DIR.glob("*.wav"))
    if not wavs:
        print(f"No WAV files in {DATA_DIR}")
        return 1

    problems = 0
    for wav in wavs:
        name = wav.stem
        if not name.isidentifier():
            print(f"ERROR  {wav.name}: the name must be a valid C identifier")
            problems += 1
            continue
        try:
            description = describe_wav(wav)
        except ValueError as e:
            print(f"ERROR  {wav.name}: {e}")
            problems += 1
            continue

        header = SOUNDS_DIR / f"{name}.h"
        if update(header, render_header(name, wav.read_bytes(), description), args.check) and args.check:
            problems += 1

    sounds_id = fingerprint(wavs)
    for path, content in [(ID_FILE, sounds_id + "\n"), (ID_HEADER, render_id_header(sounds_id))]:
        if update(path, content, args.check) and args.check:
            problems += 1
    print(f"sounds id {sounds_id}")

    for header in sorted(SOUNDS_DIR.glob("*.h")):
        if header != ID_HEADER and not (DATA_DIR / f"{header.stem}.wav").exists():
            print(f"note   {header.name} has no data/{header.stem}.wav")

    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
