#pragma once

// Generated by software/tools/wav2h.py from data/*.wav - do not edit.
// Fingerprint of the WAV files; data/sounds.id holds the same value.

constexpr const char* cSoundsId = "1d538107";
